### ISSUE TITLE
Auto indentation for one-line statements

### ISSUE THREAD

**Issue by eliaskg** [textmate/javascript.tmbundle#4]
In JavaScript often one-line statements are used.

Instead of 

```
if (true) {
    doSomething();
}
```

you often use

```
if (true)
    doSomething();
```

But the auto indentation of Textmate 2 always wants to indent the last line to

```
if (true)
doSomething();
```

Here is a short video that shows how it looks like in Textmate: http://cl.ly/2a3q3Q1R1W1X2o3N062n

**Comment by appden** [comment]
Thank you for fixing this! :heart:

**Comment by whitlockjc** [comment]
Glad to hear it's working.
