### ISSUE TITLE
Comments.tmPreferences is ignored?

### ISSUE THREAD

**Issue by lastobelus** [textmate/javascript.tmbundle#43]
Currently the Javascript bundle does block comments `/*..*/`, regardless of how many lines are in the selection.

I would like to have line comments `//`. However, when I edit `Preferences/Comments.tmPreferences` (with Xcode) it has no effect.

I was able to get line comments by editing `Source.tmbundle/Preferences/Comments.plist`, but I don't want to make the change globally, just for javascript.

**Comment by whitlockjc** [comment]
I'm not seeing this issue.  The latest TextMate for me comments block comments and single line comments just fine.  Are you using a custom bundle that might had broken something or has not been udpated?

**Comment by lastobelus** [comment]
Not sure. I did a search for all Comments.{plist,tmPreferences} and didn't see any that would be overriding it -- plus if that was the case, changing the prefs in Source bundle wouldn't change the behaviour. It seems that for some reason the Comments.tmPreferences in this bundle is being ignored.

**Comment by whitlockjc** [comment]
@infininight Any idea?  It's working for me.

**Comment by infininight** [comment]
@lastobelus Open a new file with the JavaScript grammar active and hit `⌃⌘T` (Control-command-T). This will bring up the `Select Bundle Item` window, click on the `Settings` tab, enter `comment`. This will show you all preference items that include the word `comment` and which have been overridden, etc.

The first three should be from the Javascript bundle in a pristine install.

Going to close this issue since the bundle is correct but continue to discuss the issue here.

**Comment by lastobelus** [comment]
@infininight No, the javascript bundle's prefs don't show up at all. Strange. In any case, by setting up the Source bundle prefs I have it doing what I want for the time being.

**Comment by infininight** [comment]
@lastobelus Are the items from the source bundle the only ones listed?

**Comment by lastobelus** [comment]
Yes. Also, in the Bundle Editor the comment preferences aren't listed in the Javascript bundle, only the other 3 preferences plists.

**Comment by infininight** [comment]
@lastobelus OK, your Javascript bundle isn't loading correctly then or you have a conflict somewhere else. You can reset you bundles with these steps:

https://github.com/textmate/textmate/wiki/Reverting-To-Defaults

Only steps 1-3 are needed in this case. Note that this will reset your bundles entirely including any custom bundles, as well as removing any unsaved document changes open in TextMate.
