### ISSUE TITLE
Function calls not highlighted for most/all themes

### ISSUE THREAD

**Issue by Jakeii** [textmate/javascript.tmbundle#44]
Themes seem to apply the desired color for function calls to `meta.function-call` rather than `meta.function`
https://github.com/textmate/javascript.tmbundle/blob/master/Syntaxes/JavaScript.plist#L642

Is this a mistake here, or in every `.tmTheme` I could find?

**Comment by infininight** [comment]
We generally don't intend for function calls to be colored as there are not possible to fully match in many languages so the scope is not really standardized. However it is `meta.function-call` in many other languages so I've made the change here as well.

I've just deployed the change, your bundle should update within a few hours.
