### ISSUE TITLE
ES6 Template Literals

### ISSUE THREAD

**Issue by cycomachead** [textmate/javascript.tmbundle#45]
Following #42 I think it'd be great to have strings that are template literals, show as they do in CoffeeScript.  This should show as a string: `` `Hello, ${name}` ``. Additionally, it'd be great if the `${}` could be colored slightly differently...I'm not good enough to really make this work, but here is my progress.

I was able to get the string stuff working simply by adding:
```
{	name = 'string.interpolated.js';
			begin = '`';
			end = '`';
			beginCaptures = { 0 = { name = 'punctuation.definition.string.begin.js'; }; };
			endCaptures = { 0 = { name = 'punctuation.definition.string.end.js'; }; };
			patterns = (
				{	name = 'constant.character.escape.js';
					match = '\\(x\h{2}|[0-2][0-7]{0,2}|3[0-6][0-7]|37[0-7]?|[4-7][0-7]?|.)';
				},
                                { inlcude = '#interpolated_js' }
			);
		}
```
```
repository =  {
interpolated_js = {
			patterns = (
				{	name = 'meta.embedded.line.js';
					begin = '\$\{';
					end = '(\})';
					beginCaptures = { 0 = { name = 'punctuation.section.embedded.begin.js'; }; };
					endCaptures = {
						0 = { name = 'punctuation.section.embedded.end.js'; };
						1 = { name = 'source.js'; };
					};
					contentName = 'source.js';
					patterns = ( { include = '$self'; } );
				},
			);
		};
}
```

**Comment by noniq** [comment]
:+1: I customized my JavaScript bundle in the same way, works fine. There’s a small typo in your first code snippet, though: 

```                                
                                { inlcude = '#interpolated_js' }
```
should read
```
                                { include = '#interpolated_js'; }
```

**Comment by noniq** [comment]
I’d really love to see this merged. 

Has there already been a decision on how to deal with ES6 features in general (integrate into the main grammar, or use separate grammar)?

**Comment by infininight** [comment]
The grammar has now been updated to support this and many other ECMAScript 6 features, we'll be keeping everything in one grammar. We'll be keeping the main grammar focused on browser work however, matching stuff like node.js would be better in an injected or separate grammar.
