### ISSUE TITLE
beautifier mangles `.catch()`

### ISSUE THREAD

**Issue by brandondrew** [textmate/javascript.tmbundle#46]
If I run the following code through jsbeautifier, it manges the `.catch()` so that 

    deleteBars: function (request, response) {
      return Foo.bar(request.body.barIds, baz)
      .then(function (bars) {
        return Promise.all(_.map(bars, function (bar) {
          return bar.destroy();
        }));
      })
      .then(function () {
        response.sendStatus(200);
      })
      .catch (function (error) {
        response.sendStatus(403);
      });
    }

becomes 

    deleteBars: function (request, response) {
      return Foo.bar(request.body.barIds, baz)
        .then(function (bars) {
          return Promise.all(_.map(bars, function (bar) {
            return bar.destroy();
          }));
        })
        .then(function () {
          response.sendStatus(200);
        })
        .
      catch (function (error) {
        response.sendStatus(403);
      });
    }

This is not the behavior you get on http://jsbeautifier.org/

**Comment by infininight** [comment]
I have updated to the latest version of JSBeautifier, this should correct this and many other issues.

**Comment by brandondrew** [comment]
thanks!
