### ISSUE TITLE
Class Declaration Inheritance: Support more than identifiers

### ISSUE THREAD

**Issue by infininight** [textmate/javascript.tmbundle#48]
Class declarations can inherit through arbitrary expressions, examples:

``` javascript
class Rectangle extends aggregation(Shape, Colored, ZCoord) {
  /* ... */
}

class MyClass extends Mixin1(Mixin2(MyBaseClass)) {  
  /* ... */
}
```

This is `LeftHandSideExpression` in the ECMAScript spec.

**Comment by koenpunt** [comment]
Probably the same;

Using nested objects highlights as invalid:

![image](https://cloud.githubusercontent.com/assets/351038/17324037/d2a50f66-58a4-11e6-8bc0-5775c6fca491.png)

**VS**

![image](https://cloud.githubusercontent.com/assets/351038/17324057/ea52a07e-58a4-11e6-9723-037b268354bf.png)

**Comment by jjeising** [comment]
A similar issues applies for exports:

```
export default withRouter(connect({})(ExampleClass));
```
Here `withRouter` gets `variable.other.module.js`, but should be a function.

**Comment by infininight** [comment]
Class declarations fixed thanks to @patrickrgaffney. @jjeising feel free to open a new issue about export statements.
