### ISSUE TITLE
Long Strings Break Syntax Highlighting

### ISSUE THREAD

**Issue by jonahaaron** [textmate/javascript.tmbundle#53]
Somewhere around 4085 characters in a string seems to prevent syntax highlighting from working from that point on in the JS file.

![screen shot 2016-11-30 at 10 02 49 am](https://cloud.githubusercontent.com/assets/684916/20760032/582bd474-b6e4-11e6-9776-66ba8c5aa45a.png)

**Comment by infininight** [comment]
This is a limitation imposed by TextMate due to the line length. Extremely long lines take a long time to process so the decision was made to speed up editing while sacrificing highlighting.
